#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TongJi.Web.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Repository")]
	public partial class CMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcms_attachment(cms_attachment instance);
    partial void Updatecms_attachment(cms_attachment instance);
    partial void Deletecms_attachment(cms_attachment instance);
    partial void Insertcms_comment(cms_comment instance);
    partial void Updatecms_comment(cms_comment instance);
    partial void Deletecms_comment(cms_comment instance);
    partial void Insertcms_content(cms_content instance);
    partial void Updatecms_content(cms_content instance);
    partial void Deletecms_content(cms_content instance);
    partial void Insertcms_channel(cms_channel instance);
    partial void Updatecms_channel(cms_channel instance);
    partial void Deletecms_channel(cms_channel instance);
    partial void Insertcms_vote(cms_vote instance);
    partial void Updatecms_vote(cms_vote instance);
    partial void Deletecms_vote(cms_vote instance);
    partial void Insertcms_vote_option(cms_vote_option instance);
    partial void Updatecms_vote_option(cms_vote_option instance);
    partial void Deletecms_vote_option(cms_vote_option instance);
    #endregion
		
		public CMSDataContext() : 
				base(global::TongJi.Web.Properties.Settings.Default.RepositoryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cms_attachment> cms_attachment
		{
			get
			{
				return this.GetTable<cms_attachment>();
			}
		}
		
		public System.Data.Linq.Table<cms_comment> cms_comment
		{
			get
			{
				return this.GetTable<cms_comment>();
			}
		}
		
		public System.Data.Linq.Table<cms_content> cms_content
		{
			get
			{
				return this.GetTable<cms_content>();
			}
		}
		
		public System.Data.Linq.Table<cms_channel> cms_channel
		{
			get
			{
				return this.GetTable<cms_channel>();
			}
		}
		
		public System.Data.Linq.Table<cms_vote> cms_vote
		{
			get
			{
				return this.GetTable<cms_vote>();
			}
		}
		
		public System.Data.Linq.Table<cms_vote_option> cms_vote_option
		{
			get
			{
				return this.GetTable<cms_vote_option>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_attachment")]
	public partial class cms_attachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _filename;
		
		private System.DateTime _post_time;
		
		private int _fk_content_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void Onpost_timeChanging(System.DateTime value);
    partial void Onpost_timeChanged();
    partial void Onfk_content_idChanging(int value);
    partial void Onfk_content_idChanged();
    #endregion
		
		public cms_attachment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_time", DbType="DateTime NOT NULL")]
		public System.DateTime post_time
		{
			get
			{
				return this._post_time;
			}
			set
			{
				if ((this._post_time != value))
				{
					this.Onpost_timeChanging(value);
					this.SendPropertyChanging();
					this._post_time = value;
					this.SendPropertyChanged("post_time");
					this.Onpost_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_content_id", DbType="Int NOT NULL")]
		public int fk_content_id
		{
			get
			{
				return this._fk_content_id;
			}
			set
			{
				if ((this._fk_content_id != value))
				{
					this.Onfk_content_idChanging(value);
					this.SendPropertyChanging();
					this._fk_content_id = value;
					this.SendPropertyChanged("fk_content_id");
					this.Onfk_content_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_comment")]
	public partial class cms_comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _text;
		
		private System.DateTime _post_time;
		
		private int _fk_content_id;
		
		private string _author;
		
		private string _ip;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Onpost_timeChanging(System.DateTime value);
    partial void Onpost_timeChanged();
    partial void Onfk_content_idChanging(int value);
    partial void Onfk_content_idChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    #endregion
		
		public cms_comment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_time", DbType="DateTime NOT NULL")]
		public System.DateTime post_time
		{
			get
			{
				return this._post_time;
			}
			set
			{
				if ((this._post_time != value))
				{
					this.Onpost_timeChanging(value);
					this.SendPropertyChanging();
					this._post_time = value;
					this.SendPropertyChanged("post_time");
					this.Onpost_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_content_id", DbType="Int NOT NULL")]
		public int fk_content_id
		{
			get
			{
				return this._fk_content_id;
			}
			set
			{
				if ((this._fk_content_id != value))
				{
					this.Onfk_content_idChanging(value);
					this.SendPropertyChanging();
					this._fk_content_id = value;
					this.SendPropertyChanged("fk_content_id");
					this.Onfk_content_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_content")]
	public partial class cms_content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _author;
		
		private System.DateTime _post_time;
		
		private string _text;
		
		private int _fk_channel_id;
		
		private bool _fix_to_top;
		
		private bool _enabled;
		
		private bool _allow_comment;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void Onpost_timeChanging(System.DateTime value);
    partial void Onpost_timeChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void Onfk_channel_idChanging(int value);
    partial void Onfk_channel_idChanged();
    partial void Onfix_to_topChanging(bool value);
    partial void Onfix_to_topChanged();
    partial void OnenabledChanging(bool value);
    partial void OnenabledChanged();
    partial void Onallow_commentChanging(bool value);
    partial void Onallow_commentChanged();
    #endregion
		
		public cms_content()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this.OnauthorChanging(value);
					this.SendPropertyChanging();
					this._author = value;
					this.SendPropertyChanged("author");
					this.OnauthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_time", DbType="DateTime NOT NULL")]
		public System.DateTime post_time
		{
			get
			{
				return this._post_time;
			}
			set
			{
				if ((this._post_time != value))
				{
					this.Onpost_timeChanging(value);
					this.SendPropertyChanging();
					this._post_time = value;
					this.SendPropertyChanged("post_time");
					this.Onpost_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_channel_id", DbType="Int NOT NULL")]
		public int fk_channel_id
		{
			get
			{
				return this._fk_channel_id;
			}
			set
			{
				if ((this._fk_channel_id != value))
				{
					this.Onfk_channel_idChanging(value);
					this.SendPropertyChanging();
					this._fk_channel_id = value;
					this.SendPropertyChanged("fk_channel_id");
					this.Onfk_channel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fix_to_top", DbType="Bit NOT NULL")]
		public bool fix_to_top
		{
			get
			{
				return this._fix_to_top;
			}
			set
			{
				if ((this._fix_to_top != value))
				{
					this.Onfix_to_topChanging(value);
					this.SendPropertyChanging();
					this._fix_to_top = value;
					this.SendPropertyChanged("fix_to_top");
					this.Onfix_to_topChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enabled", DbType="Bit NOT NULL")]
		public bool enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				if ((this._enabled != value))
				{
					this.OnenabledChanging(value);
					this.SendPropertyChanging();
					this._enabled = value;
					this.SendPropertyChanged("enabled");
					this.OnenabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allow_comment", DbType="Bit NOT NULL")]
		public bool allow_comment
		{
			get
			{
				return this._allow_comment;
			}
			set
			{
				if ((this._allow_comment != value))
				{
					this.Onallow_commentChanging(value);
					this.SendPropertyChanging();
					this._allow_comment = value;
					this.SendPropertyChanged("allow_comment");
					this.Onallow_commentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_channel")]
	public partial class cms_channel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _fk_father_id;
		
		private bool _enabled;
		
		private bool _has_main;
		
		private int _brother_index;
		
		private int _display_mode;
		
		private string _link;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onfk_father_idChanging(int value);
    partial void Onfk_father_idChanged();
    partial void OnenabledChanging(bool value);
    partial void OnenabledChanged();
    partial void Onhas_mainChanging(bool value);
    partial void Onhas_mainChanged();
    partial void Onbrother_indexChanging(int value);
    partial void Onbrother_indexChanged();
    partial void Ondisplay_modeChanging(int value);
    partial void Ondisplay_modeChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public cms_channel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_father_id", DbType="Int NOT NULL")]
		public int fk_father_id
		{
			get
			{
				return this._fk_father_id;
			}
			set
			{
				if ((this._fk_father_id != value))
				{
					this.Onfk_father_idChanging(value);
					this.SendPropertyChanging();
					this._fk_father_id = value;
					this.SendPropertyChanged("fk_father_id");
					this.Onfk_father_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enabled", DbType="Bit NOT NULL")]
		public bool enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				if ((this._enabled != value))
				{
					this.OnenabledChanging(value);
					this.SendPropertyChanging();
					this._enabled = value;
					this.SendPropertyChanged("enabled");
					this.OnenabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_main", DbType="Bit NOT NULL")]
		public bool has_main
		{
			get
			{
				return this._has_main;
			}
			set
			{
				if ((this._has_main != value))
				{
					this.Onhas_mainChanging(value);
					this.SendPropertyChanging();
					this._has_main = value;
					this.SendPropertyChanged("has_main");
					this.Onhas_mainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brother_index", DbType="Int NOT NULL")]
		public int brother_index
		{
			get
			{
				return this._brother_index;
			}
			set
			{
				if ((this._brother_index != value))
				{
					this.Onbrother_indexChanging(value);
					this.SendPropertyChanging();
					this._brother_index = value;
					this.SendPropertyChanged("brother_index");
					this.Onbrother_indexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_mode", DbType="Int NOT NULL")]
		public int display_mode
		{
			get
			{
				return this._display_mode;
			}
			set
			{
				if ((this._display_mode != value))
				{
					this.Ondisplay_modeChanging(value);
					this.SendPropertyChanging();
					this._display_mode = value;
					this.SendPropertyChanged("display_mode");
					this.Ondisplay_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(MAX)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_vote")]
	public partial class cms_vote : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private bool _enabled;
		
		private System.DateTime _start_time;
		
		private bool _can_vote;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnenabledChanging(bool value);
    partial void OnenabledChanged();
    partial void Onstart_timeChanging(System.DateTime value);
    partial void Onstart_timeChanged();
    partial void Oncan_voteChanging(bool value);
    partial void Oncan_voteChanged();
    #endregion
		
		public cms_vote()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enabled", DbType="Bit NOT NULL")]
		public bool enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				if ((this._enabled != value))
				{
					this.OnenabledChanging(value);
					this.SendPropertyChanging();
					this._enabled = value;
					this.SendPropertyChanged("enabled");
					this.OnenabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime NOT NULL")]
		public System.DateTime start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_vote", DbType="Bit NOT NULL")]
		public bool can_vote
		{
			get
			{
				return this._can_vote;
			}
			set
			{
				if ((this._can_vote != value))
				{
					this.Oncan_voteChanging(value);
					this.SendPropertyChanging();
					this._can_vote = value;
					this.SendPropertyChanged("can_vote");
					this.Oncan_voteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_vote_option")]
	public partial class cms_vote_option : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _fk_vote_id;
		
		private int _votes;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onfk_vote_idChanging(int value);
    partial void Onfk_vote_idChanged();
    partial void OnvotesChanging(int value);
    partial void OnvotesChanged();
    #endregion
		
		public cms_vote_option()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vote_id", DbType="Int NOT NULL")]
		public int fk_vote_id
		{
			get
			{
				return this._fk_vote_id;
			}
			set
			{
				if ((this._fk_vote_id != value))
				{
					this.Onfk_vote_idChanging(value);
					this.SendPropertyChanging();
					this._fk_vote_id = value;
					this.SendPropertyChanged("fk_vote_id");
					this.Onfk_vote_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_votes", DbType="Int NOT NULL")]
		public int votes
		{
			get
			{
				return this._votes;
			}
			set
			{
				if ((this._votes != value))
				{
					this.OnvotesChanging(value);
					this.SendPropertyChanging();
					this._votes = value;
					this.SendPropertyChanged("votes");
					this.OnvotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
