<?xml version="1.0" encoding="utf-8"?><Database Name="CityMis" Class="WorkflowDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=D:\svnRoot\CityWebGis\CityMis\App_Data\CityMis.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="TongJi.Web.Properties.Settings" SettingsPropertyName="CityMisConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.entity_attachment" Member="entity_attachment">
    <Type Name="entity_attachment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_flow_inst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_data" Member="entity_data">
    <Type Name="entity_data">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_field_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_flow_inst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_enum" Member="entity_enum">
    <Type Name="entity_enum">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_enum_member" Member="entity_enum_member">
    <Type Name="entity_enum_member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entity_enum_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_field" Member="entity_field">
    <Type Name="entity_field">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="datatype" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fk_form_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_enum_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="validation_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="validation_param" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_flow" Member="entity_flow">
    <Type Name="entity_flow">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fk_form_id_main" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_flow_inst" Member="entity_flow_inst">
    <Type Name="entity_flow_inst">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_flow_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_state_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_form" Member="entity_form">
    <Type Name="entity_form">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="def" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.entity_form_inst" Member="entity_form_inst">
    <Type Name="entity_form_inst">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_form_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_flow_inst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.entity_log" Member="entity_log">
    <Type Name="entity_log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_flow_inst_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_operation_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_operation" Member="entity_operation">
    <Type Name="entity_operation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_usergroup_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_state_id_start" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_state_id_end" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_state" Member="entity_state">
    <Type Name="entity_state">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fk_flow_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.relation_flow_form" Member="relation_flow_form">
    <Type Name="relation_flow_form">
      <Column Name="fk_flow_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_form_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_user" Member="entity_user">
    <Type Name="entity_user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="info" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.entity_usergroup" Member="entity_usergroup">
    <Type Name="entity_usergroup">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.relation_user_usergroup" Member="relation_user_usergroup">
    <Type Name="relation_user_usergroup">
      <Column Name="fk_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_usergroup_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>